### ISSUE TITLE
Configure `yankring_history_dir`

### ISSUE THREAD

**Issue by sedrubal** [fisadev/fisa-nvim-config#1]
Currently the plugin `YankRing.vim` creates a `yankring_history_v2.txt` inside the home directory. You could configure the `yankring_history_dir` in order to store this file to another location:

`let g:yankring_history_dir = 'path/to/history/dir'`

**Comment by fisadev** [comment]
Good idea! I'm making it point to '~/.config/nvim/yankring_history_v2.txt'. Included in the new published beta :) (v9.5)
