### ISSUE TITLE
Any Suggestion for debug in neovim?

### ISSUE THREAD

**Issue by hek14** [fisadev/fisa-nvim-config#10]
Thank you for the great neovim-config! I am wondering if there is a way to debug python in the vim buffer directly. But I cannot find anything related to it in your config until now.

**Comment by fisadev** [comment]
Hi! In the past I used vim-debug, before switching to neovim. I'm not sure if vim-debug works on neovim, never tried that, but it probably can. Currently to debug I prefer using stuff like pudb or ipdb, outside the editor :)

**Comment by hek14** [comment]
Thank you! I am using ipdb with the terminal mode in neovim. It's pretty good.
