### ISSUE TITLE
Autocomplete stopped working

### ISSUE THREAD

**Issue by hadad95** [fisadev/fisa-nvim-config#11]
One day I did `PlugUpdate` to be up to date with the latest commits, and this somehow made auto-complete completely break. The dropdown menu shows up but it's useless, since it only matches keywords that exist in the file I'm currently editing. I did a fresh install of neovim, uninstalled all the plugins and it still doesn't work. It could be something with deoplete/jedi but I'm not sure since I'm new to the whole (n)vim environment. Hopefully you could put me in the right direction/help me figure out what I'm doing wrong? Thank you!

**Comment by hadad95** [comment]
Feel free to ignore this issue. It was a problem with deoplete and was resolved on their repo

**Comment by fisadev** [comment]
Ok! Thanks for letting me know. I love these issues that solve themselves before I even read them, hahaha.
