### ISSUE TITLE
Add emmet-vim

### ISSUE THREAD

**Issue by sedrubal** [fisadev/fisa-nvim-config#2]
In fisa-vim-config you added the [`Plug mattn/emmet-vim`](https://github.com/mattn/emmet-vim).
Is there a reason why you didn't add it here? I miss it 😉

**Comment by fisadev** [comment]
I removed it because I almost never used it. But I guess other people do, and it would be useful for me to get used to it as well, so I'm adding it back. Already included in the new beta :) (v9.5)
