### ISSUE TITLE
Add Error Checking to nvim config :)

### ISSUE THREAD

**Issue by edvm** [fisadev/fisa-nvim-config#4]
On 'fisa-vim' there is an option '\e' that list errors reported by pylint and pep8. The doc says:
"Error checking of code using Syntastic (it will detect unused variables or imports, syntax errors, and such), for several languages, highlighting the errors and warnings in the code. You can open an errors list with \e. In python, the error checking includes pep8 validation, and pylint."
It would be awsome to have this feature on nvim config too.
Thanks!

**Comment by romeroyonatan** [comment]
Try with `:lwindow`

**Comment by fisadev** [comment]
Thanks @romeroyonatan, that's actually the answer :)
